        <div class="migrationAlert">
            <h2>SciServer Altair <i>v1.9.2</i></h2>
            <p><strong>NEW:</strong> <a href="http://www.sciserver.org/support/updates/#overview1p9p1" target="_blank">SciServer 
                <em>Altair</em> <i>v1.9.2</i>&nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a>
              is now available! This release includes BOSS and eBoss flag filtering in <a href="http://skyserver.sdss.org/public/en/tools/search/SQS.aspx" target="_blank">SkyServer Spectroscopic search&nbsp<img alt=" (new window)" src="images/new_window_cyan.png"></a>, as well as an updated Apogee 
              <a href="http://skyserver.sdss.org/public/en/tools/getimg/plate.aspx" target="_blank">Plate browser &nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a>.</p>
        </div>
