       <div class="migrationAlert">
            <h2>Data Release 14</h2>
            <p><strong>NEW:</strong> SkyServer now contains data from the new SDSS Data Release 14! 
            For more information, see the <a href="http://www.sdss.org/dr14" target="_blank">
            DR14 documentation on the SDSS website.&nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a></p>
        </div>
